# Generated by Django 2.1.7 on 2019-04-19 14:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0012_auto_20190419_2001'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billingprofile',
            unique_together={('user', 'email', 'customer_id')},
        ),
    ]
