# Generated by Django 2.1.7 on 2019-04-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20190419_2025'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billingprofile',
            unique_together={('email', 'customer_id')},
        ),
    ]
