# Generated by Django 2.1.7 on 2019-04-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_auto_20190419_2042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billingprofile',
            unique_together=set(),
        ),
    ]
