# Generated by Django 2.1.7 on 2019-04-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_auto_20190419_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
