# Generated by Django 2.1.7 on 2019-04-28 14:03

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='product_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Masters\\Courses\\Python-Django\\DJANGO\\ecommerce_project\\static_cdn\\protected_media'), upload_to=products.models.upload_product_file_location),
        ),
    ]
